---
- name: Add ffmpeg repo to the sources list
  apt_repository:   repo='ppa:mc3man/trusty-media'
                    update_cache={{ update_apt_cache }}
                    state=present
                    
- name: Install ffmpeg
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
  with_items:
    - ffmpeg
